import { MasterState } from "app/routes/app.customization";

export const DEFAULT_CHATBOT_SETTINGS: MasterState = {
  chatWindow: {
    colorMode: "solid",
    primaryColor: "#D73535",
    gradientStart: "#1CB5E0",
    gradientEnd: "#000851",
    secondaryColor: "#FF937E",
    backgroundColor: "#FCF8F8",
    textColor: "#111F35",
    secondaryTextColor: "#000000",
    fontFamily: "Roboto",
    fontSize: 16,
    fontWeight: "Regular (400)",
    width: 350,
    height: 450,
    borderRadius: 12,
  },
  messageBox: {
    borderRadiusTop: 12,
    borderRadiusRight: 12,
    borderRadiusBottom: 12,
    borderRadiusLeft: 12,
    messageSpacing: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    typingStyle: "In the Msg Box",
    typingIndicator: "Dots (animated)",
    timestampDisplay: false,
  },
  welcome: {
    greeting: "👋 Welcome! How can I help you today?",
    quickQuestions: [
      "What are your best sellers?",
      "Where is my order?",
      "Can you help me find something?",
    ],
    inputPlaceholder: "Type your message here...",
    sendOnEnter: false,
    quickQuestionPadding: 8,
    quickQuestionBorderRadius: 20,
    quickQuestionFontSize: 12,
    quickQuestionGap: 8,
  },
  topNav: {
    avatar: "",
    botName: "Start Store Assistant",
    headerHeight: 60,
    headerContent: "StartStorez",
    headerFontSize: 15,
    headerFontWeight: "600",
    showOnlineStatus: true,
    onlineStatusType: "Online",
    customOnlineText: "",
  },
  position: {
    chatButtonPosition: "Left corner",
    marginRight: 30,
    marginBottom: 30,
    zIndex: 2147483647,
  },
  btnSize: {
    size: 60,
    launcherIconName: "message-circle",
    launcherIconSize: 28,
  },
  btnAnim: {
    animationType: "Static",
    transitionDuration: 300,
  },
  closeButtonAnim: {
    animationType: "Fade Out",
    transitionDuration: 300,
  },
  footer: {
    backgroundColor: "#FFFFFF",
    inputTextColor: "#333333",
    placeholderColor: "#999999",
    inputFontSize: 14,
    inputPaddingVertical: 10,
    inputPaddingHorizontal: 12,
    borderTopColor: "#EEEEEE",
    borderRadiusBottom: 12,
    sendButtonBackgroundColor: "transparent",
    sendButtonSize: 32,
    sendButtonBorderRadius: 8,
    sendButtonIconColor: "#D73535",
    sendButtonHoverOpacity: 0.9,
    sendIconName: "send",
    sendIconSize: 16,
  },
  productSlider: {
    enabled: false,
    cardWidth: 160,
    cardHeight: 240,
    cardPadding: 12,
    cardBorderRadius: 12,
    cardGap: 12,
    imageHeight: 120,
    imageBorderRadius: 8,
    titleFontSize: 14,
    priceFontSize: 14,
    showPrice: true,
    showAskButton: true,
    askButtonSize: 28,
    askButtonIconColor: "#666666",
    backgroundColor: "#FFFFFF",
    borderColor: "#E5E7EB",
    borderWidth: 1,
  },
};
